// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace InventoryManagement.Models;

public partial class CustomerSetup
{
    [Key]
    [StringLength(50)]
    public string CustomerID { get; set; }

    [StringLength(250)]
    public string CustomerName { get; set; }

    [StringLength(50)]
    public string ContactName { get; set; }

    [StringLength(50)]
    public string DealerBussinessName { get; set; }

    [StringLength(50)]
    public string Address { get; set; }

    [StringLength(150)]
    public string Email { get; set; }

    [StringLength(50)]
    public string PhoneNumber { get; set; }

    [StringLength(50)]
    public string Mobile1 { get; set; }

    [StringLength(50)]
    public string Mobile2 { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? DueLimit { get; set; }

    [StringLength(50)]
    public string Gread { get; set; }

    [StringLength(250)]
    public string CREATE_BY { get; set; }

    public DateOnly? CREATE_DATE { get; set; }

    [StringLength(50)]
    public string UPDATE_BY { get; set; }

    public DateOnly? UPDATE_DATE { get; set; }

    public bool? InActive { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? AdvanceAmt { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? DueAmount { get; set; }
}